export const REQUEST = {
  START: 'App/REQUEST/START',
  SUCCESS: 'App/REQUEST/SUCCESS',
  ERROR: 'App/REQUEST/ERROR',
};

export const SESSION = {
  LOGIN: 'App/SESSION/LOGIN',
  LOGIN_SUCCESS: 'App/SESSION/LOGIN_SUCCESS',
  LOGOUT: 'App/SESSION/LOGOUT',
};

export const COUNTER = {
  INCREMENT: 'App/COUNTER/INCREMENT',
  DECREMENT: 'App/COUNTER/DECREMENT',
};

export const REDUX_FORM = {
  RESET: 'redux-form/RESET',
};
